"""
fetch_transcripts.py

Reads the video lists cached by fetch_youtube_videos.py and pulls a
transcript for each video, then writes a clean markdown file into:

    research/youtube-transcripts/<expert-id>/<video_id>.md

Two transcript sources are supported, in this order of preference:

  1. youtube-transcript-api (free, no key, scrapes YouTube's caption track)
  2. Supadata API (paid/free-tier transcript API mentioned in the brief) —
     used as a fallback if the free method fails or is rate-limited.

Usage:
    python scripts/fetch_transcripts.py
    python scripts/fetch_transcripts.py --expert ben-lang
    python scripts/fetch_transcripts.py --source supadata

Requires:
    pip install youtube-transcript-api requests
    (optional) SUPADATA_API_KEY in .env for the fallback path
"""

import argparse
import json
import os
import sys

import requests

from utils import (
    load_env,
    load_experts,
    ensure_expert_dirs,
    write_markdown,
    polite_sleep,
    log,
    ROOT_DIR,
)

CACHE_DIR = ROOT_DIR / "scripts" / ".cache"
SUPADATA_API_BASE = "https://api.supadata.ai/v1"


def fetch_transcript_free(video_id: str):
    """Use youtube-transcript-api — free, no API key required."""
    from youtube_transcript_api import YouTubeTranscriptApi
    from youtube_transcript_api._errors import TranscriptsDisabled, NoTranscriptFound

    try:
        transcript_list = YouTubeTranscriptApi.get_transcript(video_id)
    except (TranscriptsDisabled, NoTranscriptFound) as e:
        raise RuntimeError(f"No transcript available via free method: {e}")

    full_text = " ".join(chunk["text"] for chunk in transcript_list)
    return full_text


def fetch_transcript_supadata(video_id: str, api_key: str):
    """Fallback: Supadata transcript API."""
    headers = {"x-api-key": api_key}
    params = {"url": f"https://www.youtube.com/watch?v={video_id}"}
    resp = requests.get(f"{SUPADATA_API_BASE}/youtube/transcript", headers=headers, params=params, timeout=20)
    resp.raise_for_status()
    data = resp.json()
    # Supadata returns a list of {text, offset, duration} segments
    segments = data.get("content", data.get("transcript", []))
    if isinstance(segments, list):
        return " ".join(seg.get("text", "") for seg in segments)
    return str(segments)


def build_markdown(expert_name: str, video: dict, transcript: str, source: str) -> str:
    return f"""# {video['title']}

- **Expert:** {expert_name}
- **Video URL:** {video['url']}
- **Published:** {video.get('published_at', 'unknown')}
- **Transcript source:** {source}
- **Collected:** auto-generated by fetch_transcripts.py

## Description (from API)

{video.get('description', '').strip() or '_No description returned by API._'}

## Transcript

{transcript.strip() or '_Transcript empty or unavailable._'}

## Summary

> Fill in after review — what does this video actually teach about
> community-led growth (acquisition / activation / engagement / retention /
> advocacy / monetization)? Avoid generic restatement of the title.

## Key Lessons

- 
- 

## Mentioned Tools / Frameworks

- 
"""


def main():
    parser = argparse.ArgumentParser(description="Fetch transcripts for cached video lists.")
    parser.add_argument("--expert", default=None, help="Limit to a single expert id")
    parser.add_argument(
        "--source",
        choices=["free", "supadata"],
        default="free",
        help="Transcript source to try first (default: free)",
    )
    args = parser.parse_args()

    load_env()
    experts = {e["id"]: e for e in load_experts()}
    if args.expert:
        if args.expert not in experts:
            log.error(f"No expert with id '{args.expert}' in config/experts.json")
            sys.exit(1)
        experts = {args.expert: experts[args.expert]}

    if not CACHE_DIR.exists():
        log.error("No cached video lists found. Run fetch_youtube_videos.py first.")
        sys.exit(1)

    supadata_key = os.environ.get("SUPADATA_API_KEY")

    for expert_id, expert in experts.items():
        cache_path = CACHE_DIR / f"videos_{expert_id}.json"
        if not cache_path.exists():
            log.warning(f"No cached videos for {expert['name']} — skipping (run fetch_youtube_videos.py first).")
            continue

        with open(cache_path, "r", encoding="utf-8") as f:
            cached = json.load(f)

        yt_dir, _ = ensure_expert_dirs(expert_id)

        for video in cached["videos"]:
            video_id = video["video_id"]
            transcript, used_source = "", args.source

            try:
                if args.source == "free":
                    transcript = fetch_transcript_free(video_id)
                else:
                    if not supadata_key:
                        raise RuntimeError("SUPADATA_API_KEY not set in .env")
                    transcript = fetch_transcript_supadata(video_id, supadata_key)
            except Exception as primary_error:
                log.warning(f"{video_id}: primary source failed ({primary_error}). Trying fallback...")
                try:
                    if args.source == "free" and supadata_key:
                        transcript = fetch_transcript_supadata(video_id, supadata_key)
                        used_source = "supadata (fallback)"
                    elif args.source == "supadata":
                        transcript = fetch_transcript_free(video_id)
                        used_source = "free (fallback)"
                    else:
                        log.error(f"{video_id}: no fallback available, leaving transcript empty.")
                except Exception as fallback_error:
                    log.error(f"{video_id}: fallback also failed ({fallback_error}).")

            md = build_markdown(expert["name"], video, transcript, used_source)
            out_path = yt_dir / f"{video_id}.md"
            write_markdown(out_path, md)
            polite_sleep(1.0)  # be polite to free-tier scraping endpoints


if __name__ == "__main__":
    main()
